version: "3.9"

services:
  api:
    build:
      context: .
    platform: linux/amd64
#    command: python manage.py runserver 0.0.0.0:8000
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
#      migration:
#        condition: service_completed_successfully
      db:
        condition: service_healthy
    volumes:
      - ./.env:/code/.env
    ports:
      - 8000:8000
    env_file:
      - .env

#  migration:
#    build:
#      context: .
#    depends_on:
#      db:
#        condition: service_healthy
#    command: python manage.py migrate
#    volumes:
#      - ./.env:/code/.env

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

