# Generated by Django 4.1.5 on 2023-01-04 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("indication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indication",
            options={"verbose_name": "Инструкция", "verbose_name_plural": "Инструкции"},
        ),
        migrations.AlterField(
            model_name="indication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
