# Generated by Django 4.1.5 on 2023-01-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[("running", "в работе"), ("broken", "сломана")],
                        default="running",
                        max_length=7,
                    ),
                ),
                ("date_created", models.DateField(auto_now_add=True)),
                ("date_broken", models.DateField(blank=True, null=True)),
                ("x", models.IntegerField(default=100)),
                ("y", models.IntegerField(default=100)),
                ("z", models.IntegerField(default=100)),
            ],
        ),
    ]
