# Generated by Django 4.1.5 on 2023-01-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="station",
            options={"verbose_name": "Станция", "verbose_name_plural": "Станции"},
        ),
    ]
